export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const FETCHING_WEATHER = 'FETCHING_WEATHER';
export const LOAD_FORECAST = 'LOAD_FORECAST';
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS';
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE';
