export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const FETCHING_WEATHER = 'FETCHING_WEATHER';
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS';
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE';


export const TRACKING_LOCATION = 'TRACKING_LOCATION';
export const TRACKING_LOCATION_SUCCESSFUL = 'TRACKING_LOCATION_SUCCESSFUL';
export const TRACKING_LOCATION_FAILURE = 'TRACKING_LOCATION_FAILURE'

export const CHANGE_UNIT = 'CHANGE_UNIT';
