export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const FETCHING_WEATHER = 'FETCHING_WEATHER';
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE';
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS';
